version: "3"
services:
  nginx:
    ports:
      - "5000:80"

  shop-api:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - MONGODB=mongodb://mongo:27017/shop-api-dev
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    command: npm run start:dev

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - "27018:27017"
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
